"""
Page 7 — Credit Analyst Agent

A chat-style interface where credit officers ask natural language questions
and receive SHAP/LIME-backed explanations generated by a local SLM via llama.cpp.

Architecture
────────────
  User query (st.chat_input)
      ↓
  Intent classifier (regex, no LLM needed for routing)
      ↓
  Tool dispatcher → computes structured context (SHAP values, fairness metrics)
      ↓
  Prompt builder → fills a tight template with real numbers
      ↓
  llama.cpp subprocess → local GGUF model (Phi-3-mini or Qwen2.5-1.5B)
      ↓
  Streamed response (st.write_stream via generator)

SLM backend
───────────
  Runtime : llama.cpp CLI binary  (llama-cli.exe on Windows, llama-cli on Linux/Mac)
  Model   : any GGUF ≤ 4B params — recommended Phi-3-mini-4k-instruct Q4_K_M (~2.2 GB)
            or Qwen2.5-1.5B-Instruct Q4_K_M (~1.0 GB) for lower RAM
  No Python build step required — the binary is a standalone executable.
  Falls back to a deterministic template response when the binary is not found.

Session state consumed
──────────────────────
  processed_df    : pd.DataFrame  — full feature matrix + target
  feature_names   : list[str]     — post-encoding column names
  label_map       : dict          — {0:'P1', 1:'P2', 2:'P3', 3:'P4'}
  lr_model / ebm_model            — trained sklearn / EBM models
  X_test, y_test                  — test split (for fairness queries)
  model_metrics                   — evaluation dict from Page 3
  external_df                     — raw external dataset (sensitive attrs)
  chat_history                    — list[dict] conversation log
"""

import os
import re
import json
import shutil
import subprocess
import textwrap
import tempfile
from pathlib import Path

import streamlit as st
import pandas as pd
import numpy as np
from app.components.model_loader import load_model as _load_model_from_disk
from app.components.utils        import get_label_map, get_X_y
from app.components.shap_plotter import get_shap_values, shap_top_features

# ── Constants ─────────────────────────────────────────────────────────────────
TARGET_COL  = "Approved_Flag"
MODEL_DIR   = "app/models"
_LABEL_MAP  = {0: "P1", 1: "P2", 2: "P3", 3: "P4"}

TIER_DESCRIPTIONS = {
    "P1": "Excellent creditworthiness — approve, best terms",
    "P2": "Good creditworthiness — approve, standard terms",
    "P3": "Marginal — conditional approval or higher rate",
    "P4": "Poor creditworthiness — reject or secured product only",
}

# llama.cpp binary name (platform-aware)
_LLAMA_BIN_CANDIDATES = [
    "llama-cli",          # Linux / Mac (installed to PATH)
    "llama-cli.exe",      # Windows (installed to PATH)
    "llama-cli",          # relative path fallback
    "./llama-cli",
    "./llama-cli.exe",
]

# Recommended GGUF models (user downloads one of these)
RECOMMENDED_MODELS = {
    "Phi-3-mini-4k-instruct Q4_K_M (~2.2 GB)":
        "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/"
        "Phi-3-mini-4k-instruct-q4.gguf",
    "Qwen2.5-1.5B-Instruct Q4_K_M (~1.0 GB)":
        "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/"
        "qwen2.5-1.5b-instruct-q4_k_m.gguf",
    "Llama-3.2-1B-Instruct Q4_K_M (~0.7 GB)":
        "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/"
        "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
}

# ── Intent patterns ───────────────────────────────────────────────────────────
# Each pattern returns (intent_name, extracted_args_dict)

_INTENT_PATTERNS = [
    # explain applicant N  — matches "explain applicant 42", "why was applicant 15 rejected?"
    (r"(?:explain|why|reason|tell me about).*?applicant\s+(\d+)",
     "explain_applicant", lambda m: {"idx": int(m.group(1))}),
    # compare applicants N and M
    (r"compare\s+applicants?\s+(\d+)\s+(?:and|vs\.?|with)\s+(\d+)",
     "compare_applicants", lambda m: {"idx_a": int(m.group(1)), "idx_b": int(m.group(2))}),
    # global feature importance
    (r"(?:what|which)\s+(?:features?|factors?)\s+(?:drive|matter|important|affect)",
     "global_importance", lambda m: {}),
    (r"(?:global|overall)\s+(?:importance|shap|features?)",
     "global_importance", lambda m: {}),
    # fairness query
    (r"(?:fairness|bias|fair|discriminat)\s+(?:for\s+)?(\w+)?",
     "fairness", lambda m: {"attr": m.group(1) or "GENDER"}),
    # model performance
    (r"(?:how\s+(?:good|accurate|well)|performance|metrics?|f1|auc|accuracy)",
     "model_performance", lambda m: {}),
    # help
    (r"(?:help|what can you do|commands?|examples?)",
     "help", lambda m: {}),
]


# ── Session state helpers ─────────────────────────────────────────────────────

def _label_map() -> dict:
    return get_label_map()


def _load_model(filename: str, session_key: str):
    return _load_model_from_disk(filename, session_key)


def _get_X_y():
    return get_X_y()


def _get_X_y():
    """Return (X, y) from processed_df as named DataFrame."""
    df = st.session_state.get("processed_df")
    if df is None:
        return None, None
    feature_names = st.session_state.get(
        "feature_names", [c for c in df.columns if c != TARGET_COL]
    )
    return df[feature_names], df.get(TARGET_COL)


# ── SHAP computation — delegated to shap_plotter component ───────────────────

def _get_shap_values(model, X: pd.DataFrame, model_key: str):
    """Cache key prefixed with 'agent_' to separate from Page 4/5 caches."""
    return get_shap_values(model, X, f"agent_{model_key}")


def _top_shap_features(shap_values, idx: int, n: int = 5) -> list[tuple[str, float]]:
    return shap_top_features(shap_values, idx, n)


def _shap_delta(shap_values, idx_a: int, idx_b: int, n: int = 5) -> list[tuple[str, float, float]]:
    """Return top-n features by |delta SHAP| between two applicants."""
    sv_a = shap_values[idx_a]
    sv_b = shap_values[idx_b]
    vals_a = sv_a.values.mean(axis=1) if sv_a.values.ndim == 2 else sv_a.values
    vals_b = sv_b.values.mean(axis=1) if sv_b.values.ndim == 2 else sv_b.values
    delta  = vals_b - vals_a
    top_idx = np.argsort(np.abs(delta))[::-1][:n]
    return [(sv_a.feature_names[i], float(vals_a[i]), float(vals_b[i])) for i in top_idx]


# ── llama.cpp subprocess backend ─────────────────────────────────────────────

def _find_llama_binary() -> str | None:
    """Return path to llama-cli binary, or None if not found."""
    for candidate in _LLAMA_BIN_CANDIDATES:
        if shutil.which(candidate):
            return candidate
        if Path(candidate).exists():
            return candidate
    return None


def _run_llama(prompt: str, model_path: str, n_predict: int = 300, temperature: float = 0.3) -> str:
    """
    Run llama-cli with the given prompt and return the generated text.

    Uses --no-display-prompt so only the completion is returned.
    Runs CPU-only (no GPU flags) for maximum portability.
    Context window set to 2048 — sufficient for credit explanation prompts.
    """
    binary = _find_llama_binary()
    if binary is None:
        return ""

    cmd = [
        binary,
        "--model",       model_path,
        "--prompt",      prompt,
        "--n-predict",   str(n_predict),
        "--temp",        str(temperature),
        "--ctx-size",    "2048",
        "--threads",     str(max(1, os.cpu_count() // 2)),
        "--no-display-prompt",
        "--log-disable",
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,   # 2-minute hard limit
        )
        output = result.stdout.strip()
        # Strip any residual prompt echo that some versions include
        if prompt.strip() in output:
            output = output.replace(prompt.strip(), "").strip()
        return output
    except subprocess.TimeoutExpired:
        return "[Generation timed out after 120 seconds. Try a smaller model or reduce n_predict.]"
    except FileNotFoundError:
        return ""
    except Exception as e:
        return f"[llama.cpp error: {e}]"


# ── Prompt templates ──────────────────────────────────────────────────────────

def _build_explain_prompt(
    idx: int,
    pred_class: str,
    confidence: float,
    top_features: list[tuple[str, float]],
    label_map: dict,
) -> str:
    feat_lines = "\n".join(
        f"  {i+1}. {name}: {val:+.4f} ({'increases' if val > 0 else 'decreases'} approval chance)"
        for i, (name, val) in enumerate(top_features)
    )
    tier_desc = TIER_DESCRIPTIONS.get(pred_class, "")
    return textwrap.dedent(f"""
        You are a credit analyst AI for an Indian bank. Explain the following credit decision
        in plain English. Be concise (3-4 sentences). End with one actionable recommendation.

        Applicant index: {idx}
        Predicted credit tier: {pred_class} — {tier_desc}
        Confidence: {confidence:.1%}

        Top SHAP feature contributions (positive = supports approval):
        {feat_lines}

        Format your response as:
        DECISION: [one sentence stating the outcome]
        REASONS: [2-3 bullet points with the key factors]
        RECOMMENDATION: [one actionable sentence for the applicant]
    """).strip()


def _build_compare_prompt(
    idx_a: int, pred_a: str, conf_a: float,
    idx_b: int, pred_b: str, conf_b: float,
    delta_features: list[tuple[str, float, float]],
) -> str:
    delta_lines = "\n".join(
        f"  {name}: applicant {idx_a}={va:+.4f}, applicant {idx_b}={vb:+.4f} (delta={vb-va:+.4f})"
        for name, va, vb in delta_features
    )
    return textwrap.dedent(f"""
        You are a credit analyst AI. Compare two loan applicants and explain the key differences.
        Be concise (4-5 sentences total).

        Applicant {idx_a}: tier {pred_a} ({conf_a:.1%} confidence)
        Applicant {idx_b}: tier {pred_b} ({conf_b:.1%} confidence)

        Largest SHAP differences between the two applicants:
        {delta_lines}

        Explain why applicant {idx_b} received a {'better' if pred_b < pred_a else 'worse'} tier
        than applicant {idx_a}, referencing the specific features above.
    """).strip()


def _build_global_prompt(top_global: list[tuple[str, float]]) -> str:
    feat_lines = "\n".join(
        f"  {i+1}. {name} (mean |SHAP| = {val:.4f})"
        for i, (name, val) in enumerate(top_global)
    )
    return textwrap.dedent(f"""
        You are a credit analyst AI for an Indian bank. Explain what drives credit approval
        decisions in this model, based on the global SHAP feature importance below.
        Write 3-4 sentences in plain English for a non-technical audience.

        Top 10 most important features (by mean absolute SHAP value):
        {feat_lines}

        Focus on what these features mean in a credit context and why they matter.
    """).strip()


def _build_fairness_prompt(attr: str, dpd: float, eod: float, sr_dict: dict) -> str:
    sr_lines = "\n".join(
        f"  {group}: {rate:.1%} approval rate"
        for group, rate in sorted(sr_dict.items(), key=lambda x: -x[1])
    )
    return textwrap.dedent(f"""
        You are a credit analyst AI explaining fairness metrics to a bank compliance officer.
        Be concise and professional (3-4 sentences).

        Fairness analysis for attribute: {attr}
        Demographic Parity Difference: {dpd:.4f}
        Equalized Odds Difference: {eod:.4f}

        Approval rates by group:
        {sr_lines}

        Thresholds: <0.05 acceptable, 0.05-0.10 monitor, >0.10 action required.
        Explain what these numbers mean and whether action is needed.
    """).strip()


def _build_performance_prompt(metrics: dict) -> str:
    lr  = metrics.get("lr", {})
    ebm = metrics.get("ebm", {})
    return textwrap.dedent(f"""
        You are a credit analyst AI explaining model performance to a bank manager.
        Write 3-4 sentences in plain English. Avoid technical jargon.

        Model performance on {metrics.get('n_test', 'N/A'):,} test applicants:

        Logistic Regression:
          - Macro F1: {lr.get('f1_macro', 0):.3f}
          - AUC (OvR): {lr.get('auc_ovr', 0):.3f}

        Explainable Boosting Machine (EBM):
          - Macro F1: {ebm.get('f1_macro', 0):.3f}
          - AUC (OvR): {ebm.get('auc_ovr', 0):.3f}

        Explain what these numbers mean for the bank's credit decisions.
    """).strip()


# ── Fallback template responses (no SLM required) ────────────────────────────

def _fallback_explain(idx, pred_class, confidence, top_features) -> str:
    tier_desc = TIER_DESCRIPTIONS.get(pred_class, "")
    top3 = top_features[:3]
    reasons = "\n".join(
        f"  • **{name}**: SHAP contribution {val:+.4f} "
        f"({'positive' if val > 0 else 'negative'} impact on approval)"
        for name, val in top3
    )
    rec_feature = top3[0][0] if top3 else "credit utilization"
    return (
        f"**DECISION:** Applicant {idx} was classified as **{pred_class}** "
        f"({tier_desc}) with {confidence:.1%} confidence.\n\n"
        f"**REASONS:**\n{reasons}\n\n"
        f"**RECOMMENDATION:** Focus on improving `{rec_feature}` — "
        f"it has the largest impact on this applicant's credit tier."
    )


def _fallback_compare(idx_a, pred_a, conf_a, idx_b, pred_b, conf_b, delta_features) -> str:
    top = delta_features[:3]
    lines = "\n".join(
        f"  • **{name}**: applicant {idx_a} = {va:+.4f}, applicant {idx_b} = {vb:+.4f}"
        for name, va, vb in top
    )
    return (
        f"**Applicant {idx_a}**: {pred_a} ({conf_a:.1%} confidence)\n"
        f"**Applicant {idx_b}**: {pred_b} ({conf_b:.1%} confidence)\n\n"
        f"**Key differences:**\n{lines}"
    )


def _fallback_global(top_global) -> str:
    lines = "\n".join(
        f"  {i+1}. **{name}** (mean |SHAP| = {val:.4f})"
        for i, (name, val) in enumerate(top_global[:10])
    )
    return f"**Top features driving credit decisions:**\n{lines}"


def _fallback_fairness(attr, dpd, eod, sr_dict) -> str:
    lines = "\n".join(
        f"  • **{g}**: {r:.1%}" for g, r in sorted(sr_dict.items(), key=lambda x: -x[1])
    )
    dpd_status = "✅ Acceptable" if dpd < 0.05 else ("⚠️ Monitor" if dpd < 0.10 else "🚨 Action Required")
    eod_status = "✅ Acceptable" if eod < 0.05 else ("⚠️ Monitor" if eod < 0.10 else "🚨 Action Required")
    return (
        f"**Fairness analysis for {attr}:**\n\n"
        f"Approval rates by group:\n{lines}\n\n"
        f"**Demographic Parity Difference:** {dpd:.4f} — {dpd_status}\n"
        f"**Equalized Odds Difference:** {eod:.4f} — {eod_status}"
    )


def _fallback_performance(metrics) -> str:
    lr  = metrics.get("lr", {})
    ebm = metrics.get("ebm", {})
    return (
        f"**Model performance on {metrics.get('n_test', 'N/A'):,} test applicants:**\n\n"
        f"| Model | Macro F1 | AUC (OvR) |\n"
        f"|-------|----------|----------|\n"
        f"| Logistic Regression | {lr.get('f1_macro', 0):.3f} | {lr.get('auc_ovr', 0):.3f} |\n"
        f"| EBM | {ebm.get('f1_macro', 0):.3f} | {ebm.get('auc_ovr', 0):.3f} |"
    )


def _help_text() -> str:
    return textwrap.dedent("""
        **Credit Analyst Agent — example queries:**

        - `explain applicant 42` — why was this applicant approved or rejected?
        - `compare applicants 5 and 12` — what's different between two applicants?
        - `what features drive approvals?` — global model explanation
        - `fairness for GENDER` — demographic parity analysis
        - `fairness for EDUCATION` — education-level bias check
        - `how accurate is the model?` — performance metrics

        The agent uses SHAP values from the trained model to ground every explanation
        in actual feature contributions, not generic statements.
    """).strip()


# ── Intent classification ─────────────────────────────────────────────────────

def _classify_intent(query: str) -> tuple[str, dict]:
    """
    Match query against intent patterns.
    Returns (intent_name, args_dict).
    Falls back to 'unknown' if no pattern matches.
    """
    q = query.lower().strip()
    for pattern, intent, extractor in _INTENT_PATTERNS:
        m = re.search(pattern, q)
        if m:
            return intent, extractor(m)
    return "unknown", {}


# ── Tool dispatcher ───────────────────────────────────────────────────────────

def _dispatch(
    intent: str,
    args: dict,
    model,
    model_key: str,
    X: pd.DataFrame,
    y: pd.Series,
    label_map: dict,
    model_path: str | None,
    metrics: dict | None,
    external_df: pd.DataFrame | None,
    X_test: pd.DataFrame | None,
    y_test: pd.Series | None,
) -> str:
    """
    Execute the tool for the given intent, build a prompt, run the SLM,
    and return the response string.
    Falls back to template if SLM binary or model file is unavailable.
    """
    use_slm = (model_path is not None) and Path(model_path).exists() and (_find_llama_binary() is not None)

    # ── explain applicant ─────────────────────────────────────────────────────
    if intent == "explain_applicant":
        idx = args.get("idx", 0)
        if idx >= len(X):
            return f"Applicant index {idx} is out of range (dataset has {len(X)} rows)."

        shap_values = _get_shap_values(model, X, model_key)
        top_features = _top_shap_features(shap_values, idx, n=5)

        y_pred_int  = int(model.predict(X.iloc[[idx]])[0])
        pred_class  = label_map.get(y_pred_int, str(y_pred_int))
        proba       = model.predict_proba(X.iloc[[idx]])[0]
        confidence  = float(proba[list(model.classes_).index(y_pred_int)])

        if use_slm:
            prompt = _build_explain_prompt(idx, pred_class, confidence, top_features, label_map)
            response = _run_llama(prompt, model_path)
            if response:
                return response

        return _fallback_explain(idx, pred_class, confidence, top_features)

    # ── compare applicants ────────────────────────────────────────────────────
    elif intent == "compare_applicants":
        idx_a = args.get("idx_a", 0)
        idx_b = args.get("idx_b", 1)
        n = len(X)
        if idx_a >= n or idx_b >= n:
            return f"Index out of range. Dataset has {n} rows (0–{n-1})."

        shap_values = _get_shap_values(model, X, model_key)
        delta = _shap_delta(shap_values, idx_a, idx_b, n=5)

        def _pred_info(idx):
            y_int  = int(model.predict(X.iloc[[idx]])[0])
            cls    = label_map.get(y_int, str(y_int))
            proba  = model.predict_proba(X.iloc[[idx]])[0]
            conf   = float(proba[list(model.classes_).index(y_int)])
            return cls, conf

        pred_a, conf_a = _pred_info(idx_a)
        pred_b, conf_b = _pred_info(idx_b)

        if use_slm:
            prompt = _build_compare_prompt(idx_a, pred_a, conf_a, idx_b, pred_b, conf_b, delta)
            response = _run_llama(prompt, model_path)
            if response:
                return response

        return _fallback_compare(idx_a, pred_a, conf_a, idx_b, pred_b, conf_b, delta)

    # ── global importance ─────────────────────────────────────────────────────
    elif intent == "global_importance":
        shap_values = _get_shap_values(model, X, model_key)
        sv_vals = shap_values.values
        if sv_vals.ndim == 3:
            importance = np.abs(sv_vals).mean(axis=(0, 2))
        else:
            importance = np.abs(sv_vals).mean(axis=0)
        top_idx    = np.argsort(importance)[::-1][:10]
        top_global = [(shap_values.feature_names[i], float(importance[i])) for i in top_idx]

        if use_slm:
            prompt = _build_global_prompt(top_global)
            response = _run_llama(prompt, model_path)
            if response:
                return response

        return _fallback_global(top_global)

    # ── fairness ──────────────────────────────────────────────────────────────
    elif intent == "fairness":
        attr = args.get("attr", "GENDER").upper()
        if external_df is None or X_test is None or y_test is None:
            return "Fairness analysis requires the full pipeline to be run first (Upload → Preprocess → Train)."

        # Recover sensitive attribute at test indices
        if attr not in external_df.columns:
            available = [c for c in ["GENDER", "EDUCATION", "MARITALSTATUS"] if c in external_df.columns]
            return f"Attribute `{attr}` not found. Available: {available}"

        try:
            sensitive = external_df.loc[X_test.index, attr].reset_index(drop=True)
        except KeyError:
            sensitive = external_df[attr].iloc[:len(X_test)].reset_index(drop=True)

        y_pred_raw = model.predict(X_test)
        y_pred_bin = pd.Series(y_pred_raw).isin({0, 1}).astype(int)
        y_true_bin = y_test.reset_index(drop=True).isin({0, 1}).astype(int)

        sr = y_pred_bin.groupby(sensitive.values).mean()
        dpd = float(sr.max() - sr.min())

        df_tmp = pd.DataFrame({"y_true": y_true_bin.values, "y_pred": y_pred_bin.values, "group": sensitive.values})
        tpr = df_tmp[df_tmp.y_true == 1].groupby("group")["y_pred"].mean()
        fpr = df_tmp[df_tmp.y_true == 0].groupby("group")["y_pred"].mean()
        eod = float(max(
            tpr.max() - tpr.min() if len(tpr) > 1 else 0,
            fpr.max() - fpr.min() if len(fpr) > 1 else 0,
        ))

        sr_dict = sr.to_dict()

        if use_slm:
            prompt = _build_fairness_prompt(attr, dpd, eod, sr_dict)
            response = _run_llama(prompt, model_path)
            if response:
                return response

        return _fallback_fairness(attr, dpd, eod, sr_dict)

    # ── model performance ─────────────────────────────────────────────────────
    elif intent == "model_performance":
        if metrics is None:
            return "No model metrics found. Run **Train Models** first."

        if use_slm:
            prompt = _build_performance_prompt(metrics)
            response = _run_llama(prompt, model_path)
            if response:
                return response

        return _fallback_performance(metrics)

    # ── help ──────────────────────────────────────────────────────────────────
    elif intent == "help":
        return _help_text()

    # ── unknown ───────────────────────────────────────────────────────────────
    else:
        return (
            "I didn't understand that query. Try:\n"
            "- `explain applicant 42`\n"
            "- `compare applicants 5 and 12`\n"
            "- `what features drive approvals?`\n"
            "- `fairness for GENDER`\n"
            "- `help` for all examples"
        )


# ── Main page ─────────────────────────────────────────────────────────────────

def main():
    st.title("🤖 Credit Analyst Agent")
    st.caption(
        "Ask questions in plain English. "
        "Answers are grounded in SHAP feature contributions from the trained model."
    )

    # ── SLM setup sidebar ─────────────────────────────────────────────────────
    with st.sidebar:
        st.markdown("### ⚙️ SLM Configuration")

        binary_found = _find_llama_binary()
        if binary_found:
            st.success(f"llama-cli found: `{binary_found}`")
        else:
            st.warning("llama-cli not found in PATH")
            with st.expander("How to install llama.cpp"):
                st.markdown(textwrap.dedent("""
                    **Option 1 — Pre-built binary (recommended)**
                    Download from the [llama.cpp releases page](https://github.com/ggerganov/llama.cpp/releases)
                    and place `llama-cli.exe` (Windows) or `llama-cli` (Linux/Mac) in your PATH
                    or in the project root directory.

                    **Option 2 — Build from source**
                    ```bash
                    git clone https://github.com/ggerganov/llama.cpp
                    cd llama.cpp
                    cmake -B build
                    cmake --build build --config Release
                    ```
                    Then copy `build/bin/llama-cli` to your PATH.
                """))

        model_path = st.text_input(
            "GGUF model path",
            value=st.session_state.get("agent_model_path", ""),
            placeholder="/path/to/model.gguf",
            help="Path to a local GGUF model file. Leave empty to use template responses.",
        )
        if model_path:
            st.session_state["agent_model_path"] = model_path
            if Path(model_path).exists():
                size_gb = Path(model_path).stat().st_size / 1e9
                st.success(f"Model found ({size_gb:.1f} GB)")
            else:
                st.error("File not found")
                model_path = None

        with st.expander("Recommended models"):
            for name, url in RECOMMENDED_MODELS.items():
                st.markdown(f"**{name}**")
                st.code(f"# Download with:\nwget {url}", language="bash")

        st.markdown("---")
        st.markdown("**Mode:**")
        if binary_found and model_path and Path(model_path).exists():
            st.success("🟢 SLM active (llama.cpp)")
        else:
            st.info("🔵 Template mode (no SLM)")
            st.caption("Responses use structured templates with real SHAP numbers. Install llama.cpp + a GGUF model for natural language generation.")

    # ── Load dependencies ─────────────────────────────────────────────────────
    X, y = _get_X_y()
    if X is None:
        st.error("Run **Preprocessing** and **Train Models** first.")
        return

    lr  = _load_model("logistic_regression.pkl", "lr_model")
    ebm = _load_model("ebm_model.pkl",           "ebm_model")

    model_options = {}
    if lr:  model_options["Logistic Regression"] = ("lr",  lr)
    if ebm: model_options["EBM"]                 = ("ebm", ebm)

    if not model_options:
        st.error("No trained models found. Run **Train Models** first.")
        return

    model_display_key = st.selectbox("Model", list(model_options.keys()), key="agent_model_select")
    model_key, model  = model_options[model_display_key]

    label_map   = _label_map()
    metrics     = st.session_state.get("model_metrics")
    external_df = st.session_state.get("external_df")
    X_test      = st.session_state.get("X_test")
    y_test      = st.session_state.get("y_test")
    model_path  = st.session_state.get("agent_model_path") or None

    # ── Chat history ──────────────────────────────────────────────────────────
    if "chat_history" not in st.session_state:
        st.session_state["chat_history"] = []

    # Render existing conversation
    for msg in st.session_state["chat_history"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    # ── Chat input ────────────────────────────────────────────────────────────
    if query := st.chat_input("Ask about an applicant, feature importance, or fairness..."):

        # Show user message
        with st.chat_message("user"):
            st.markdown(query)
        st.session_state["chat_history"].append({"role": "user", "content": query})

        # Classify intent
        intent, args = _classify_intent(query)

        # Dispatch and generate response
        with st.chat_message("assistant"):
            with st.spinner("Analysing..."):
                response = _dispatch(
                    intent=intent,
                    args=args,
                    model=model,
                    model_key=model_key,
                    X=X,
                    y=y,
                    label_map=label_map,
                    model_path=model_path,
                    metrics=metrics,
                    external_df=external_df,
                    X_test=X_test,
                    y_test=y_test,
                )
            st.markdown(response)

        st.session_state["chat_history"].append({"role": "assistant", "content": response})

    # ── Clear history button ──────────────────────────────────────────────────
    if st.session_state["chat_history"]:
        if st.button("🗑 Clear conversation"):
            st.session_state["chat_history"] = []
            st.rerun()

    st.markdown("---")
    st.info("➡ Proceed to **Business Summary** for ₹ NPA impact framing.")


if __name__ == "__main__":
    main()
